//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the available currencies. Please try again later..
        /// </summary>
        internal static string apiServiceFailMessage {
            get {
                return ResourceManager.GetString("apiServiceFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available currencies are:.
        /// </summary>
        internal static string availableCurrenciesMessage {
            get {
                return ResourceManager.GetString("availableCurrenciesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format is incorrect. Correct format is dd.MM.yyyy (e.g., 01.01.2020).
        /// </summary>
        internal static string dateInvalidMessage {
            get {
                return ResourceManager.GetString("dateInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t request a date earlier than 4 years from now..
        /// </summary>
        internal static string dateInvalidPeriodMessage {
            get {
                return ResourceManager.GetString("dateInvalidPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the exchange rate. Please try again later..
        /// </summary>
        internal static string exchangeRateAPIFailMessage {
            get {
                return ResourceManager.GetString("exchangeRateAPIFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /get_currencies.
        /// </summary>
        internal static string getCurrenciesCommandString {
            get {
                return ResourceManager.GetString("getCurrenciesCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available for this currency. Please enter a valid currency code. For example: USD..
        /// </summary>
        internal static string invalidCurrencyCodeMessage {
            get {
                return ResourceManager.GetString("invalidCurrencyCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a message in the format: &lt;currency code&gt; &lt;date&gt;.
        /// </summary>
        internal static string invalidFormatMessage {
            get {
                return ResourceManager.GetString("invalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        internal static string startCommandString {
            get {
                return ResourceManager.GetString("startCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Please send a message in the format: &lt;currency code&gt; &lt;date&gt;. For example: USD 01.01.2022. The command to see a list of all currencies - /get_currencies.
        /// </summary>
        internal static string startMessage {
            get {
                return ResourceManager.GetString("startMessage", resourceCulture);
            }
        }
    }
}
